// Builds the live-page runtime from runtime-src/:
//   public/runtime/core.{js,css}     always loaded on live pages
//   public/runtime/m/<name>.{js,css} one per interactive widget, loaded only by pages that use it
//   public/runtime.{js,css}          everything in one file (editor canvas, and embeds published before the split)
// Run: node scripts/build-runtime.mjs (also runs before `dev` and `build`).
import fs from "node:fs";
import path from "node:path";

const src = path.resolve("runtime-src");
const out = path.resolve("public");
const read = (f) => fs.readFileSync(f, "utf8");

fs.mkdirSync(path.join(out, "runtime", "m"), { recursive: true });

const coreJs = read(path.join(src, "core.js"));
const coreCss = read(path.join(src, "core.css"));
fs.writeFileSync(path.join(out, "runtime", "core.js"), coreJs);
fs.writeFileSync(path.join(out, "runtime", "core.css"), coreCss);

const modules = fs
  .readdirSync(path.join(src, "modules"))
  .map((f) => f.replace(/\.(js|css)$/, ""))
  .filter((v, i, a) => a.indexOf(v) === i)
  .sort();

let allJs = coreJs;
let allCss = coreCss;
for (const name of modules) {
  for (const ext of ["js", "css"]) {
    const file = path.join(src, "modules", `${name}.${ext}`);
    if (!fs.existsSync(file)) continue;
    const code = read(file);
    fs.writeFileSync(path.join(out, "runtime", "m", `${name}.${ext}`), code);
    if (ext === "js") allJs += "\n" + code;
    else allCss += "\n" + code;
  }
}
const banner = "/* Generated by scripts/build-runtime.mjs from runtime-src/. Edit those files instead. */\n";
fs.writeFileSync(path.join(out, "runtime.js"), banner + allJs);
fs.writeFileSync(path.join(out, "runtime.css"), banner + allCss);
fs.writeFileSync(path.join(out, "runtime", "modules.json"), JSON.stringify(modules));
console.log(`runtime: core + ${modules.length} modules`);
