// Generates src/lib/widgets/icon-data.ts: curated outline icons from lucide-static (ISC) and a few
// social brand marks from simple-icons (CC0).
// Run: node scripts/gen-icons.mjs
import fs from "node:fs";
import path from "node:path";

const NAMES = `
check check-check circle-check circle-check-big square-check x circle-x plus minus circle-plus info circle-alert triangle-alert circle-help
star heart thumbs-up award trophy medal crown gem sparkles flame zap rocket target crosshair badge-check badge-percent
shield shield-check lock lock-open key fingerprint eye
clock timer hourglass calendar calendar-check calendar-days alarm-clock history
phone phone-call mail mail-open send message-circle message-square messages-square at-sign inbox bell megaphone
map-pin map navigation globe compass building building-2 store house home
user users user-check user-plus circle-user contact handshake smile baby person-standing
trending-up trending-down chart-line chart-bar chart-pie chart-column activity gauge percent calculator
dollar-sign euro pound-sterling indian-rupee credit-card wallet banknote coins piggy-bank receipt shopping-cart shopping-bag tag tags gift package truck
briefcase laptop monitor smartphone tablet tv camera image video film mic headphones music play circle-play
book book-open graduation-cap school pencil pen-tool brush palette scissors ruler
wrench hammer settings cog sliders-horizontal plug battery-charging lightbulb flask-conical microscope atom
heart-pulse stethoscope pill syringe activity hospital cross dumbbell bike footprints apple salad coffee utensils pizza cake
leaf tree-pine sun moon cloud umbrella snowflake mountain waves droplet flower
car plane ship train bus
paw-print dog cat bird fish
file file-text clipboard clipboard-check folder download upload link external-link share-2 paperclip printer
search filter list list-checks layout-grid layers grid-3x3 menu ellipsis
arrow-right arrow-left arrow-up arrow-down arrow-up-right chevron-right chevron-left chevron-down chevron-up move-right circle-arrow-right
refresh-cw rotate-ccw repeat infinity
wifi cloud-upload server database cpu code terminal bot brain-circuit
quote ticket key-round
`.split(/\s+/).filter(Boolean);

const dir = path.resolve("node_modules/lucide-static/icons");
const out = {};
const missing = [];
for (const name of [...new Set(NAMES)]) {
  const file = path.join(dir, `${name}.svg`);
  if (!fs.existsSync(file)) {
    missing.push(name);
    continue;
  }
  const svg = fs.readFileSync(file, "utf8");
  // Keep only the inner shapes; the wrapper <svg> is rebuilt at render time.
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s+/g, " ")
    .replace(/> </g, "><")
    .trim();
  out[name] = inner;
}

const BRANDS = ["facebook", "instagram", "x", "youtube", "tiktok", "whatsapp", "pinterest", "threads", "github", "discord", "telegram", "google", "yelp", "vimeo"];
const brands = {};
for (const name of BRANDS) {
  const svg = fs.readFileSync(path.resolve(`node_modules/simple-icons/icons/${name}.svg`), "utf8");
  const d = svg.match(/<path d="([^"]+)"/)?.[1];
  if (d) brands[name] = d;
}

const entries = (obj) =>
  Object.entries(obj)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");
fs.writeFileSync(
  path.resolve("src/lib/widgets/icon-data.ts"),
  `/* Generated by scripts/gen-icons.mjs from lucide-static (ISC) and simple-icons (CC0). Do not edit by hand. */

/** Outline icons: inner SVG markup for a 24×24, stroke="currentColor" canvas. */
export const ICON_PATHS: Record<string, string> = {
${entries(out)}
};

/** Filled brand marks: a single path on a 24×24 canvas. */
export const BRAND_PATHS: Record<string, string> = {
${entries(brands)}
};
`,
);
console.log(`icons: ${Object.keys(out).length}, brands: ${Object.keys(brands).length}, missing: ${missing.join(", ") || "none"}`);
